#-------------------------------------------------------------------------------
# Header
#-------------------------------------------------------------------------------
# Description: need metro median scores by race and metro child pop by race, and for the 100 largest metros combined

# clear environment
rm(list=ls()); gc()

# libraries
library(RMariaDB)
library(tidyverse)
library(data.table)

# functions
source("resources/fun/SQL_load.R")

# path
HOME <- "C:/Users/bdevoe/Desktop/SQL/viz_data"


#-------------------------------------------------------------------------------
# load and merge data
#-------------------------------------------------------------------------------

# load geo ids
geo <- SQL_load(database = "COI30_2025", table_id = "COI30_TRACT_GEO_20", overwrite = F, noisily = F)
geo <- select(geo, c(metro_name, in100))
geo <- unique(geo)
rm(HOME, SQL_load)

# metro normed metro medians
metro_medians <- fread("C:/Users/bdevoe/Desktop/SQL/METROS/COI_20_metros_nat_medians/COI_20_metros_nat_medians.csv")

# merge geo ids data
metro_medians <- left_join(metro_medians, geo)
rm(geo)

# metro counts
metro_count <- fread("C:/Users/bdevoe/Desktop/SQL/METROS/COI_20_metros_met_counts/COI_20_metros_met_counts.csv")
metro_count <- select(metro_count, c("metro_fips", "year", "group",
                                     "very_low","low","moderate","high","very_high"))

# merged metro data
metro_medians <- full_join(metro_medians, metro_count, by = c("metro_fips", "year", "group"))
rm(metro_count)

#-------------------------------------------------------------------------------
# process data
#-------------------------------------------------------------------------------

# filter rows to top 100 metros
metro_medians <- filter(metro_medians, in100 == 1 | metro_name == "top100_metros")

# filter rows to 2023
metro_medians <- filter(metro_medians, year == "2023")

# filter out num_tracts
metro_medians <- filter(metro_medians, group != "num_tracts")

# filter to all lvl
metro_medians <- filter(metro_medians, lbl == "all")

# create total population count
#TODO: should I pull population count from acs data or just add it together with
#      the metro count data generated by our aggregation script?
colSums(is.na(metro_medians))
metro_medians$population <- metro_medians$very_low + metro_medians$low + metro_medians$moderate + metro_medians$high + metro_medians$very_high

# select columns
metro_medians <- select(metro_medians, c(metro_name, year, group, median_opp_score, population, normed))

# pivot wide
metro_medians <- pivot_wider(metro_medians, names_from = group, values_from = c(median_opp_score, population))

# sum population count for top100 metros combined
metro_medians[1, grep("^population", names(metro_medians))] <- as.list(
  colSums(metro_medians[-1, grep("^population", names(metro_medians))], na.rm = TRUE)
)


#-------------------------------------------------------------------------------
# save
#-------------------------------------------------------------------------------

fwrite(metro_medians, file = "data/output/table5.csv")



